sudo: false

language: ruby

rvm:
  - 2.3.3
  - 2.4.0

cache: bundler
script: bundle exec middleman build


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
